import fs from "fs";
import path from "path";
import { openai } from "./openaiClient";
import { collectRelatedFiles } from "./resolveDependencies";

/**
 * Generates a relative import path for a given file.
 * 
 * @param filePath - The path to the file.
 * @returns A relative import string (e.g., "./myFile").
 */
function getImportPath(filePath: string) {
    return "./" + path.basename(filePath).replace(".ts", "")
}

/**
 * Uses a regex to find the first exported function name in the provided file content.
 * 
 * @param content - The source code content.
 * @returns The name of the exported function.
 * @throws Error if no exported function is found.
 */
function extractExportedFunctionName(content: string): string {
    const match = content.match(
        /export\s+function\s+(\w+)/
    )

    if (!match) {
        throw new Error("No exported function found")
    }

    return match[1]
}

/**
 * Constructs the prompt for the OpenAI model to generate a Vitest test file.
 * 
 * @param filePath - Path of the source file.
 * @param mainContent - Content of the source file.
 * @param relatedContents - Array of contents from related dependencies or types.
 * @returns A formatted string containing the system instructions and source context.
 */
function buildPrompt(
    filePath: string,
    mainContent: string,
    relatedContents: string[]
) {
    const importPath = getImportPath(filePath)

    return `
You are a senior TypeScript engineer.

Generate a Vitest test file for the following source file.

The test file will live in the SAME folder as the source file.

Use this exact import:
import { ${extractExportedFunctionName(mainContent)} } from "${importPath}"

Requirements:
- Use Vitest
- No snapshot tests
- Cover edge cases
- Validate thrown errors where applicable
- Do not mock unless necessary
- Return ONLY raw TypeScript code
- Do NOT wrap in markdown
- Do NOT include explanations

SOURCE FILE:
${mainContent}

RELATED TYPES OR DEPENDENCIES:
${relatedContents.join("\n\n")}
`
}

/**
 * Coordinates the test generation process for a given file.
 * It collects dependencies, builds a prompt, calls the OpenAI API, and cleans the response.
 * 
 * @param filePath - Absolute path to the source file to generate tests for.
 * @returns The generated Vitest test code, stripped of markdown formatting.
 */
export async function generateTestForFile(
    filePath: string
): Promise<string> {
    // Read the main source file content
    const mainContent = fs.readFileSync(filePath, "utf-8")

    // Gather content from related files (like types) to provide more context to the LLM
    const relatedPaths = collectRelatedFiles(filePath)
    const relatedContents = relatedPaths.map((p) =>
        fs.readFileSync(p, "utf-8")
    )

    // Create the instruction prompt
    const prompt = buildPrompt(
        filePath,
        mainContent,
        relatedContents
    )

    // Request a completion from OpenAI using the gpt-4o-mini model
    const response = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [
            {
                role: "system",
                content:
                    "You are an expert TypeScript engineer specialized in writing high-quality tests.",
            },
            {
                role: "user",
                content: prompt,
            },
        ],
        temperature: 0.2, // Lower temperature for more deterministic/stable output
    })

    const content = response.choices[0].message.content

    if (!content) {
        throw new Error("No test generated by model")
    }

    // Remove any markdown fence blocks if the model included them despite instructions
    const cleaned = content
        .replace(/```typescript/g, "")
        .replace(/```/g, "")
        .trim()

    return cleaned
}

/**
 * Sends a failing test and its error output back to the model to request a fix.
 * 
 * @param filePath - Absolute path to the source file.
 * @param currentTestCode - The current (failing) test code.
 * @param vitestOutput - The error output from Vitest.
 * @returns The corrected test code.
 */
export async function fixFailingTest(
    filePath: string,
    currentTestCode: string,
    vitestOutput: string
): Promise<string> {
    const mainContent = fs.readFileSync(filePath, "utf-8")

    const prompt = `
        You generated the following Vitest test, but it is failing.

        SOURCE FILE:
        ${mainContent}

        CURRENT TEST:
        ${currentTestCode}

        VITEST ERROR OUTPUT:
        ${vitestOutput}

        Fix the test so that it passes.
        Return ONLY raw TypeScript code.
        Do NOT wrap in markdown.
    `;

    // Request a fix from OpenAI
    const response = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [
            {
                role: "system",
                content:
                    "You are an expert TypeScript engineer fixing failing tests.",
            },
            {
                role: "user",
                content: prompt,
            },
        ],
        temperature: 0.2,
    })

    const content = response.choices[0].message.content

    if (!content) {
        throw new Error("No fix generated")
    }

    // Clean up markdown formatting if present
    return content
        .replace(/```typescript/g, "")
        .replace(/```/g, "")
        .trim()
}